//
// ****************************************************************
// Copyright(c) 2008-2013 uvisual,inc. All rights reserved.
// ****************************************************************
//
// Auto generated from: DataCollection.def
// Warning: do not edit this file.
//
package DataCollection;

public final class EventType {
    public static final int kEventTypeRecord = 0;

    public static String toString(int val) {
        switch (val) {
            case kEventTypeRecord:
                return "kEventTypeRecord";
            default:
                return "unknown";
        }
    }
}
