//
// ****************************************************************
// Copyright(c) 2008-2013 uvisual,inc. All rights reserved.
// ****************************************************************
//
// Auto generated from: NoticeEvent.def
// Warning: do not edit this file.
//
package Event;

public final class NoticeEventAgent {
    public final Common.ObjectAgent __agent;

    public NoticeEventAgent(Common.ObjectAgent agent) {
        this.__agent = agent;
    }

    public final boolean verCode(final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        return verCode(__agent,params,outParams,__params);
    }

    public final void verCode_begin(final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        verCode_begin(__agent,__async,params,__params,__userdata);
    }

    public static final boolean verCode(final Common.ObjectAgent __agent,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("verCode.NoticeEvent.Event");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        Common.StrStrMap.__write(__oput,params);
                        break;
                    default: throw new Common.Exception("agent-error:ver error");
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                int __rslt = __agent.ex_sync("verCode.NoticeEvent.Event",__oput,__iput,__params);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;if (__loop >= 3) throw new Common.Exception("agent-error:vers error");
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput.value);
                        break;
                    default: throw new Common.Exception("agent-error:vers error");
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public static final void verCode_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("verCode.NoticeEvent.Event");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            Common.StrStrMap.__write(__oput,params);
                            break;
                        default: throw new Common.Exception("agent-error:vers error");
                    }
                    __agent.ex_async(this,"verCode.NoticeEvent.Event",__oput,__params,0);
                }
                catch (Common.Exception ex) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null) __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,new Common.Exception("agent-error:vers error"),__userdata);
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean verCode_end(int __rslt,Common.IputStream __iput,Common.StrStrMap.Holder outParams) {
        try {
            Common.ObjectAgent.processFirst(__rslt,__iput);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput);
                    break;
                default: throw new Common.Exception("agent-error:vers error");
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public final boolean verJoinRoom(final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        return verJoinRoom(__agent,params,outParams,__params);
    }

    public final void verJoinRoom_begin(final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        verJoinRoom_begin(__agent,__async,params,__params,__userdata);
    }

    public static final boolean verJoinRoom(final Common.ObjectAgent __agent,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("verJoinRoom.NoticeEvent.Event");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        Common.StrStrMap.__write(__oput,params);
                        break;
                    default: throw new Common.Exception("agent-error:ver error");
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                int __rslt = __agent.ex_sync("verJoinRoom.NoticeEvent.Event",__oput,__iput,__params);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;if (__loop >= 3) throw new Common.Exception("agent-error:vers error");
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput.value);
                        break;
                    default: throw new Common.Exception("agent-error:vers error");
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public static final void verJoinRoom_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("verJoinRoom.NoticeEvent.Event");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            Common.StrStrMap.__write(__oput,params);
                            break;
                        default: throw new Common.Exception("agent-error:vers error");
                    }
                    __agent.ex_async(this,"verJoinRoom.NoticeEvent.Event",__oput,__params,0);
                }
                catch (Common.Exception ex) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null) __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,new Common.Exception("agent-error:vers error"),__userdata);
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean verJoinRoom_end(int __rslt,Common.IputStream __iput,Common.StrStrMap.Holder outParams) {
        try {
            Common.ObjectAgent.processFirst(__rslt,__iput);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput);
                    break;
                default: throw new Common.Exception("agent-error:vers error");
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public final boolean roomNotice(final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        return roomNotice(__agent,params,outParams,__params);
    }

    public final void roomNotice_begin(final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        roomNotice_begin(__agent,__async,params,__params,__userdata);
    }

    public static final boolean roomNotice(final Common.ObjectAgent __agent,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("roomNotice.NoticeEvent.Event");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        Common.StrStrMap.__write(__oput,params);
                        break;
                    default: throw new Common.Exception("agent-error:ver error");
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                int __rslt = __agent.ex_sync("roomNotice.NoticeEvent.Event",__oput,__iput,__params);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;if (__loop >= 3) throw new Common.Exception("agent-error:vers error");
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput.value);
                        break;
                    default: throw new Common.Exception("agent-error:vers error");
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public static final void roomNotice_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("roomNotice.NoticeEvent.Event");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            Common.StrStrMap.__write(__oput,params);
                            break;
                        default: throw new Common.Exception("agent-error:vers error");
                    }
                    __agent.ex_async(this,"roomNotice.NoticeEvent.Event",__oput,__params,0);
                }
                catch (Common.Exception ex) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null) __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,new Common.Exception("agent-error:vers error"),__userdata);
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean roomNotice_end(int __rslt,Common.IputStream __iput,Common.StrStrMap.Holder outParams) {
        try {
            Common.ObjectAgent.processFirst(__rslt,__iput);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput);
                    break;
                default: throw new Common.Exception("agent-error:vers error");
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public final boolean recordSnapshotNotice(final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        return recordSnapshotNotice(__agent,params,outParams,__params);
    }

    public final void recordSnapshotNotice_begin(final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        recordSnapshotNotice_begin(__agent,__async,params,__params,__userdata);
    }

    public static final boolean recordSnapshotNotice(final Common.ObjectAgent __agent,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("recordSnapshotNotice.NoticeEvent.Event");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        Common.StrStrMap.__write(__oput,params);
                        break;
                    default: throw new Common.Exception("agent-error:ver error");
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                int __rslt = __agent.ex_sync("recordSnapshotNotice.NoticeEvent.Event",__oput,__iput,__params);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;if (__loop >= 3) throw new Common.Exception("agent-error:vers error");
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput.value);
                        break;
                    default: throw new Common.Exception("agent-error:vers error");
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public static final void recordSnapshotNotice_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("recordSnapshotNotice.NoticeEvent.Event");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            Common.StrStrMap.__write(__oput,params);
                            break;
                        default: throw new Common.Exception("agent-error:vers error");
                    }
                    __agent.ex_async(this,"recordSnapshotNotice.NoticeEvent.Event",__oput,__params,0);
                }
                catch (Common.Exception ex) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null) __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,new Common.Exception("agent-error:vers error"),__userdata);
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean recordSnapshotNotice_end(int __rslt,Common.IputStream __iput,Common.StrStrMap.Holder outParams) {
        try {
            Common.ObjectAgent.processFirst(__rslt,__iput);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput);
                    break;
                default: throw new Common.Exception("agent-error:vers error");
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public final boolean sendOnlineMessageAndNotice(final String receiverUri,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        return sendOnlineMessageAndNotice(__agent,receiverUri,params,outParams,__params);
    }

    public final void sendOnlineMessageAndNotice_begin(final Common.AgentAsync __async,final String receiverUri,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        sendOnlineMessageAndNotice_begin(__agent,__async,receiverUri,params,__params,__userdata);
    }

    public static final boolean sendOnlineMessageAndNotice(final Common.ObjectAgent __agent,final String receiverUri,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("sendOnlineMessageAndNotice.NoticeEvent.Event");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        __oput.write(receiverUri);
                        Common.StrStrMap.__write(__oput,params);
                        break;
                    default: throw new Common.Exception("agent-error:ver error");
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                int __rslt = __agent.ex_sync("sendOnlineMessageAndNotice.NoticeEvent.Event",__oput,__iput,__params);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;if (__loop >= 3) throw new Common.Exception("agent-error:vers error");
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput.value);
                        break;
                    default: throw new Common.Exception("agent-error:vers error");
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public static final void sendOnlineMessageAndNotice_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final String receiverUri,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("sendOnlineMessageAndNotice.NoticeEvent.Event");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            __oput.write(receiverUri);
                            Common.StrStrMap.__write(__oput,params);
                            break;
                        default: throw new Common.Exception("agent-error:vers error");
                    }
                    __agent.ex_async(this,"sendOnlineMessageAndNotice.NoticeEvent.Event",__oput,__params,0);
                }
                catch (Common.Exception ex) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null) __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,new Common.Exception("agent-error:vers error"),__userdata);
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean sendOnlineMessageAndNotice_end(int __rslt,Common.IputStream __iput,Common.StrStrMap.Holder outParams) {
        try {
            Common.ObjectAgent.processFirst(__rslt,__iput);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput);
                    break;
                default: throw new Common.Exception("agent-error:vers error");
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public final boolean keepAlive(final int type,final String username,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        return keepAlive(__agent,type,username,params,outParams,__params);
    }

    public final void keepAlive_begin(final Common.AgentAsync __async,final int type,final String username,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        keepAlive_begin(__agent,__async,type,username,params,__params,__userdata);
    }

    public static final boolean keepAlive(final Common.ObjectAgent __agent,final int type,final String username,final java.util.Map<String,String > params,Common.StrStrMap.Holder outParams,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("keepAlive.NoticeEvent.Event");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        __oput.write(type);
                        __oput.write(username);
                        Common.StrStrMap.__write(__oput,params);
                        break;
                    default: throw new Common.Exception("agent-error:ver error");
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                int __rslt = __agent.ex_sync("keepAlive.NoticeEvent.Event",__oput,__iput,__params);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;if (__loop >= 3) throw new Common.Exception("agent-error:vers error");
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput.value);
                        break;
                    default: throw new Common.Exception("agent-error:vers error");
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }

    public static final void keepAlive_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final int type,final String username,final java.util.Map<String,String > params,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("keepAlive.NoticeEvent.Event");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            __oput.write(type);
                            __oput.write(username);
                            Common.StrStrMap.__write(__oput,params);
                            break;
                        default: throw new Common.Exception("agent-error:vers error");
                    }
                    __agent.ex_async(this,"keepAlive.NoticeEvent.Event",__oput,__params,0);
                }
                catch (Common.Exception ex) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null) __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) Common.ObjectAgent.throwException(__async,new Common.Exception("agent-error:vers error"),__userdata);
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean keepAlive_end(int __rslt,Common.IputStream __iput,Common.StrStrMap.Holder outParams) {
        try {
            Common.ObjectAgent.processFirst(__rslt,__iput);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    if (outParams == null) outParams = new Common.StrStrMap.Holder();outParams.value = Common.StrStrMap.__read(__iput);
                    break;
                default: throw new Common.Exception("agent-error:vers error");
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        }
        catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            if (outParams != null) outParams.value = null;
            return false;
        }
    }
}
