//
// ****************************************************************
// Copyright(c) 2008-2013 uvisual,inc. All rights reserved.
// ****************************************************************
//
// Auto generated from: xx.def
// Warning: do not edit this file.
//
package com.juphoon.rtc.datacenter.cube.service;


import com.juphoon.rtc.datacenter.cube.model.Event;
import com.juphoon.rtc.datacenter.cube.model.EventList;

public abstract class EventCollectionServiceServer extends Common.ObjectServer {
    public abstract void event_begin(Common.ServerCall __call,java.util.List<Event> eventList) throws Common.Exception;
    public abstract void event2_begin(Common.ServerCall __call,String topic,java.util.List<Event > eventList) throws Common.Exception;

    public final boolean __ex(Common.ServerCall __call,String __cmd,Common.IputStream __iput) throws Common.Exception {
        if (__cmd.compareTo("event.EventCollectionService.DataCollection") == 0) { __cmd_event(__call,__iput);return true;}
        if (__cmd.compareTo("event.EventCollectionService.Collection") == 0) { __cmd_event(__call,__iput);return true;}
        if (__cmd.compareTo("event2.EventCollectionService.DataCollection") == 0) { __cmd_event2(__call,__iput);return true;}
        return false;
    }

    public static void event_end(Common.ServerCall __call,boolean __ret) {
        Common.VerList __vers = __call.verList();
        Common.OputStream __oput = new Common.OputStream();
        short __ver = (__vers != null)?__vers.ver(true):0;
        switch (__ver) {
            case 0:
                __oput.write(__ret);
                break;
        }
        __call.cmdResult(__ver,__oput);
    }

    private void __cmd_event(Common.ServerCall __call,Common.IputStream __iput) throws Common.Exception {
        __outer: {
            Common.VerList __vers = __call.verList();
            java.util.List<Event > eventList;
            switch (__vers.ver(false)) {
                case 0:
                    eventList = EventList.__read(__iput);
                    break;
                default: break __outer;
            }
            __start(false);
            event_begin(__call,eventList);
            return;
        }
        Common.OputStream __oput = new Common.OputStream();
        __oput.write((short)1);
        __oput.write((short)0);
        __call.cmdResult(1<<16,__oput);
    }

    public static void event2_end(Common.ServerCall __call,boolean __ret) {
        Common.VerList __vers = __call.verList();
        Common.OputStream __oput = new Common.OputStream();
        short __ver = (__vers != null)?__vers.ver(true):0;
        switch (__ver) {
            case 0:
                __oput.write(__ret);
                break;
        }
        __call.cmdResult(__ver,__oput);
    }

    private void __cmd_event2(Common.ServerCall __call,Common.IputStream __iput) throws Common.Exception {
        __outer: {
            Common.VerList __vers = __call.verList();
            String topic;
            java.util.List<Event > eventList;
            switch (__vers.ver(false)) {
                case 0:
                    topic = __iput.readString();
                    eventList = EventList.__read(__iput);
                    break;
                default: break __outer;
            }
            __start(false);
            event2_begin(__call,topic,eventList);
            return;
        }
        Common.OputStream __oput = new Common.OputStream();
        __oput.write((short)1);
        __oput.write((short)0);
        __call.cmdResult(1<<16,__oput);
    }
}
