//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: ClientConfig.def
// Warning: do not edit this file.
//
package Config;

import lombok.Data;
import lombok.Getter;

@Data
public final class ConfigInfo {
    public String appKey;
    public long version;
    public java.util.List<String > keys;
    public java.util.Map<String,String > params;

    public ConfigInfo() {
        this.appKey = "";
        this.version = (long)0;
        this.keys = null;
        this.params = null;
    }

    public ConfigInfo(String appKey,long version,java.util.List<String > keys,java.util.Map<String,String > params) {
        this.appKey = appKey;
        this.version = version;
        this.keys = keys;
        this.params = params;
    }

    public static final class Holder {
        public Holder() {
        }
        public Holder(ConfigInfo value) {
            this.value = value;
        }
        public ConfigInfo value;
    }

    public static void __write(Common.OputStream __oput, ConfigInfo __obj) {
        if (__obj == null) __obj = new ConfigInfo();
        __oput.write(__obj.appKey);
        __oput.write(__obj.version);
        Common.StrVec.__write(__oput,__obj.keys);
        Common.StrStrMap.__write(__oput,__obj.params);
    }

    public static ConfigInfo __read(Common.IputStream __iput) throws Common.Exception {
        ConfigInfo __obj = new ConfigInfo();
        __obj.appKey = __iput.readString();
        __obj.version = __iput.readLong();
        __obj.keys = Common.StrVec.__read(__iput);
        __obj.params = Common.StrStrMap.__read(__iput);
        return __obj;
    }

    public static void __textWrite(Common.OputStream __oput, String __name, ConfigInfo __obj) {
        if (__obj == null) return;
        __oput.textStart(__name);
        __oput.textWrite("appKey",__obj.appKey);
        __oput.textWrite("version",__obj.version);
        Common.StrVec.__textWrite(__oput,"keys",__obj.keys);
        Common.StrStrMap.__textWrite(__oput,"params",__obj.params);
        __oput.textEnd();
    }

    public static ConfigInfo __textRead(Common.IputStream __iput,String __name,int __idx) {
        if (!__iput.textStart(__name,__idx)) return null;
        ConfigInfo __obj = new ConfigInfo();
        __obj.appKey = __iput.textReadString("appKey",0,"");
        __obj.version = __iput.textReadLong("version",0,(long)0);
        __obj.keys = Common.StrVec.__textRead(__iput,"keys",0);
        __obj.params = Common.StrStrMap.__textRead(__iput,"params",0);
        __iput.textEnd();
        return __obj;
    }
}
