//
// ****************************************************************
// Copyright(c) 2008-2013 uvisual,inc. All rights reserved.
// ****************************************************************
//
// Auto generated from: AccountPub1.def
// Warning: do not edit this file.
//
package com.juphoon.rtc.datacenter.Account;

public final class Status {
    public static final int StatusOnline = 0;
    public static final int StatusOfflinePush = 1;
    public static final int StatusOffline = 2;
    public static final int StatusNotFound = 3;
    public static final int StatusUnknown = 4;

    public static String toString(int val){
        switch (val) {
        case StatusOnline: return "StatusOnline";
        case StatusOfflinePush: return "StatusOfflinePush";
        case StatusOffline: return "StatusOffline";
        case StatusNotFound: return "StatusNotFound";
        case StatusUnknown: return "StatusUnknown";
        default: return "unknown";
        }
    }
}
