//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: DataCollection.def
// Warning: do not edit this file.
//
package DataCollection;
@SuppressWarnings("PMD")
public final class EventCollectionServiceAgent {
    public final Common.ObjectAgent __agent;

    public EventCollectionServiceAgent(Common.ObjectAgent agent) {
        this.__agent = agent;
    }

    public final boolean event(final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params) {
        return event(__agent,eventList,__params);
    }

    public final void event_begin(final Common.AgentAsync __async,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params,final Object __userdata) {
        event_begin(__agent,__async,eventList,__params,__userdata);
    }

    public static final boolean event(final Common.ObjectAgent __agent,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("event.EventCollectionService.DataCollection");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        DataCollection.EventList.__write(__oput,eventList);
                        break;
                    default:
                        throw new Common.CallException(Common.ObjectAgent.versionError("event.EventCollectionService.DataCollection"));
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                Common.CallError.Holder __error = new Common.CallError.Holder();
                int __rslt = __agent.ex_sync("event.EventCollectionService.DataCollection",__oput,__iput,__params,__error);
                if (__rslt == -1)
                    throw new Common.CallException(__error.value);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;
                    if (__loop >= 3)
                        throw new Common.CallException(Common.ObjectAgent.versionError("event.EventCollectionService.DataCollection"));
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        break;
                    default:
                        throw new Common.CallException(Common.ObjectAgent.versionError("event.EventCollectionService.DataCollection"));
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        } catch (Common.CallException ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        } catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        }
    }

    public static final void event_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("event.EventCollectionService.DataCollection");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            DataCollection.EventList.__write(__oput,eventList);
                            break;
                        default:
                            throw new Common.CallException(Common.ObjectAgent.versionError("event.EventCollectionService.DataCollection"));
                    }
                    __agent.ex_async(this,"event.EventCollectionService.DataCollection",__oput,__params,0);
                } catch (Common.CallException ex) {
                    if (__async != null)
                        Common.ObjectAgent.throwException(__async,ex,__userdata);
                } catch (Common.Exception ex) {
                    if (__async != null)
                        Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null)
                        __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) {
                        try {
                            Common.ObjectAgent.throwException(__async,new Common.CallException(Common.ObjectAgent.versionError("event.EventCollectionService.DataCollection")),__userdata);
                        } catch (Common.Exception ex) {
                            Common.ObjectAgent.throwException(__async,ex,__userdata);
                        }
                    }
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean event_end(int __rslt,Common.IputStream __iput) {
        try {
            Common.CallError.Holder __error = new Common.CallError.Holder();
            if (Common.ObjectAgent.processException(__rslt,__iput,__error))
                throw new Common.CallException(__error.value);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    break;
                default:
                    throw new Common.CallException(Common.ObjectAgent.versionError("event.EventCollectionService.DataCollection"));
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        } catch (Common.CallException ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        } catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        }
    }

    public final boolean event2(final String topic,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params) {
        return event2(__agent,topic,eventList,__params);
    }

    public final void event2_begin(final Common.AgentAsync __async,final String topic,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params,final Object __userdata) {
        event2_begin(__agent,__async,topic,eventList,__params,__userdata);
    }

    public static final boolean event2(final Common.ObjectAgent __agent,final String topic,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params) {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("event2.EventCollectionService.DataCollection");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        __oput.write(topic);
                        DataCollection.EventList.__write(__oput,eventList);
                        break;
                    default:
                        throw new Common.CallException(Common.ObjectAgent.versionError("event2.EventCollectionService.DataCollection"));
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                Common.CallError.Holder __error = new Common.CallError.Holder();
                int __rslt = __agent.ex_sync("event2.EventCollectionService.DataCollection",__oput,__iput,__params,__error);
                if (__rslt == -1)
                    throw new Common.CallException(__error.value);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;
                    if (__loop >= 3)
                        throw new Common.CallException(Common.ObjectAgent.versionError("event2.EventCollectionService.DataCollection"));
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        break;
                    default:
                        throw new Common.CallException(Common.ObjectAgent.versionError("event2.EventCollectionService.DataCollection"));
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        } catch (Common.CallException ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        } catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        }
    }

    public static final void event2_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final String topic,final java.util.List<DataCollection.Event > eventList,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("event2.EventCollectionService.DataCollection");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            __oput.write(topic);
                            DataCollection.EventList.__write(__oput,eventList);
                            break;
                        default:
                            throw new Common.CallException(Common.ObjectAgent.versionError("event2.EventCollectionService.DataCollection"));
                    }
                    __agent.ex_async(this,"event2.EventCollectionService.DataCollection",__oput,__params,0);
                } catch (Common.CallException ex) {
                    if (__async != null)
                        Common.ObjectAgent.throwException(__async,ex,__userdata);
                } catch (Common.Exception ex) {
                    if (__async != null)
                        Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null)
                        __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) {
                        try {
                            Common.ObjectAgent.throwException(__async,new Common.CallException(Common.ObjectAgent.versionError("event2.EventCollectionService.DataCollection")),__userdata);
                        } catch (Common.Exception ex) {
                            Common.ObjectAgent.throwException(__async,ex,__userdata);
                        }
                    }
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean event2_end(int __rslt,Common.IputStream __iput) {
        try {
            Common.CallError.Holder __error = new Common.CallError.Holder();
            if (Common.ObjectAgent.processException(__rslt,__iput,__error))
                throw new Common.CallException(__error.value);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    break;
                default:
                    throw new Common.CallException(Common.ObjectAgent.versionError("event2.EventCollectionService.DataCollection"));
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        } catch (Common.CallException ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        } catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            return false;
        }
    }

    public final boolean subEvent(final Common.CallParams __params) throws Common.Exception {
        return subEvent(__agent,__params);
    }

    public final void subEvent_begin(final Common.AgentAsync __async,final Common.CallParams __params,final Object __userdata) {
        subEvent_begin(__agent,__async,__params,__userdata);
    }

    public static final boolean subEvent(final Common.ObjectAgent __agent,final Common.CallParams __params) throws Common.Exception {
        try {
            int __loop = 0;
            while (true) {
                Common.OputStream __oput = new Common.OputStream();
                Common.VerList __vers = __agent.verList("subEvent.EventCollectionService.DataCollection");
                short __ver = 0;
                if (__vers != null) {
                    __ver = __vers.ver(true);
                    if (__ver > 0) __ver = 0;
                }
                switch (__ver) {
                    case 0:
                        __oput.write((short)1);
                        __oput.write((short)__ver);
                        break;
                    default:
                        throw new Common.CallException(Common.ObjectAgent.versionError("subEvent.EventCollectionService.DataCollection"));
                }
                Common.IputStream.Holder __iput = new Common.IputStream.Holder();
                Common.CallError.Holder __error = new Common.CallError.Holder();
                int __rslt = __agent.ex_sync("subEvent.EventCollectionService.DataCollection",__oput,__iput,__params,__error);
                if (__rslt == -1)
                    throw new Common.CallException(__error.value);
                if ((__rslt>>16) != 0) {
                    assert((__rslt>>16) == 1);
                    __loop ++;
                    if (__loop >= 3)
                        throw new Common.CallException(Common.ObjectAgent.versionError("subEvent.EventCollectionService.DataCollection"));
                    continue;
                }
                boolean __ret;
                switch (__rslt) {
                    case 0:
                        __ret = __iput.value.readBool();
                        break;
                    default:
                        throw new Common.CallException(Common.ObjectAgent.versionError("subEvent.EventCollectionService.DataCollection"));
                }
                Common.ObjectAgent.processFinal(__iput.value);
                return __ret;
            }
        } catch (Common.CallException ex) {
            Common.ObjectAgent.processFinal(ex);
            throw ex;
        } catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            throw ex;
        }
    }

    public static final void subEvent_begin(final Common.ObjectAgent __agent,final Common.AgentAsync __async,final Common.CallParams __params,final Object __userdata) {
        (new Common.AgentAsync() {
            public final void start() {
                try {
                    Common.OputStream __oput = new Common.OputStream();
                    Common.VerList __vers = __agent.verList("subEvent.EventCollectionService.DataCollection");
                    short __ver = 0;
                    if (__vers != null) {
                        __ver = __vers.ver(true);
                        if (__ver > 0) __ver = 0;
                    }
                    switch (__ver) {
                        case 0:
                            __oput.write((short)1);
                            __oput.write((short)__ver);
                            break;
                        default:
                            throw new Common.CallException(Common.ObjectAgent.versionError("subEvent.EventCollectionService.DataCollection"));
                    }
                    __agent.ex_async(this,"subEvent.EventCollectionService.DataCollection",__oput,__params,0);
                } catch (Common.CallException ex) {
                    if (__async != null)
                        Common.ObjectAgent.throwException(__async,ex,__userdata);
                } catch (Common.Exception ex) {
                    if (__async != null)
                        Common.ObjectAgent.throwException(__async,ex,__userdata);
                }
            }
            public final void cmdResult(int __rslt,Common.IputStream __iput,Object __userdata) {
                if ((__rslt>>16)!=1) {
                    if (__async != null)
                        __async.cmdResult(__rslt,__iput,__userdata);
                    return;
                }
                __loop ++;
                if (__loop >= 3) {
                    if (__async != null) {
                        try {
                            Common.ObjectAgent.throwException(__async,new Common.CallException(Common.ObjectAgent.versionError("subEvent.EventCollectionService.DataCollection")),__userdata);
                        } catch (Common.Exception ex) {
                            Common.ObjectAgent.throwException(__async,ex,__userdata);
                        }
                    }
                    return;
                }
                start();
            }
            private int __loop = 0;
        }).start();
    }

    public static final boolean subEvent_end(int __rslt,Common.IputStream __iput) throws Common.Exception {
        try {
            Common.CallError.Holder __error = new Common.CallError.Holder();
            if (Common.ObjectAgent.processException(__rslt,__iput,__error))
                throw new Common.CallException(__error.value);
            assert((__rslt>>16) == 0);
            boolean __ret;
            switch (__rslt) {
                case 0:
                    __ret = __iput.readBool();
                    break;
                default:
                    throw new Common.CallException(Common.ObjectAgent.versionError("subEvent.EventCollectionService.DataCollection"));
            }
            Common.ObjectAgent.processFinal(__iput);
            return __ret;
        } catch (Common.CallException ex) {
            Common.ObjectAgent.processFinal(ex);
            throw ex;
        } catch (Common.Exception ex) {
            Common.ObjectAgent.processFinal(ex);
            throw ex;
        }
    }
}
