//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\DataCollection.def
// Warning: do not edit this file.
//
package DataCollection;

public final class FlowList {
    public static final class Holder {
        public Holder() {
        }
        public Holder(java.util.List<DataCollection.FlowStatusJson > value) {
            this.value = value;
        }
        public java.util.List<DataCollection.FlowStatusJson > value;
    }

    public static void __write(Common.OputStream __oput,java.util.List<DataCollection.FlowStatusJson > __obj) {
        if (__obj == null)
            __oput.write((int)0);
        else {
            __oput.write((int)__obj.size());
            for(DataCollection.FlowStatusJson m:__obj)
                DataCollection.FlowStatusJson.__write(__oput,m);
        }
    }

    public static java.util.List<DataCollection.FlowStatusJson > __read(Common.IputStream __iput) throws Common.Exception {
        java.util.List<DataCollection.FlowStatusJson > __obj = new java.util.ArrayList<DataCollection.FlowStatusJson >();
        int size = __iput.readInt();
        for (int i=0;i<size;i++) {
            DataCollection.FlowStatusJson m = DataCollection.FlowStatusJson.__read(__iput);
            __obj.add(m);
        }
        return __obj;
    }

    public static void __textWrite(Common.OputStream __oput,String __name,java.util.List<DataCollection.FlowStatusJson > __obj) {
        if (__obj == null) return;
        __oput.textArray(__name);
        for(DataCollection.FlowStatusJson m:__obj) {
            DataCollection.FlowStatusJson.__textWrite(__oput,__name,m);
        }
    }

    public static java.util.List<DataCollection.FlowStatusJson > __textRead(Common.IputStream __iput,String __name,int __idx) {
        java.util.List<DataCollection.FlowStatusJson > __obj = new java.util.ArrayList<DataCollection.FlowStatusJson >();
        int size = __iput.textCount(__name);
        for (int i=0;i<size;i++) {
            DataCollection.FlowStatusJson m;
            if ((m = DataCollection.FlowStatusJson.__textRead(__iput,__name,i)) != null)
                __obj.add(m);
        }
        return __obj;
    }
}

