//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: ./DataCollection.def
// Warning: do not edit this file.
//
package DataCollection;

public abstract class GetOidCollectionServiceServer extends Common.ObjectServer {
    public abstract void gteOid_begin(Common.ServerCall __call) throws Common.Exception;

    public final boolean __ex(Common.ServerCall __call,String __cmd,Common.IputStream __iput) throws Common.Exception {
        if (__cmd.compareTo("gteOid.GetOidCollectionService.DataCollection") == 0) { __cmd_gteOid(__call,__iput);return true;}
        return false;
    }

    public static void gteOid_end(Common.ServerCall __call,boolean __ret,String oid) {
        Common.VerList __vers = __call.verList();
        Common.OputStream __oput = new Common.OputStream();
        short __ver = (__vers != null)?__vers.ver(true):0;
        switch (__ver) {
        case 0:
            __oput.write(__ret);
            __oput.write(oid);
            break;
        }
        __call.cmdResult(__ver,__oput);
    }

    private void __cmd_gteOid(Common.ServerCall __call,Common.IputStream __iput) throws Common.Exception {
        __outer: {
            Common.VerList __vers = __call.verList();
            switch (__vers.ver(false)) {
            case 0:
                break;
            default: break __outer;
            }
            __start(false);
            gteOid_begin(__call);
            return;
        }
        Common.OputStream __oput = new Common.OputStream();
        __oput.write((short)1);
        __oput.write((short)0);
        __call.cmdResult(1<<16,__oput);
    }
}
