//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\DataCollection.def
// Warning: do not edit this file.
//
package DataCollection;

public final class RecordEventAction{
    public static final int kRecordEventActionStart = 0;
    public static final int kRecordEventActionStop = 1;
    public static final int kRecordEventActionPause = 2;
    public static final int kRecordEventActionRsume = 3;
    public static final int kRecordEventActionUploading = 4;
    public static final int kRecordEventActionUploaded = 5;
    public static final int kRecordEventActionError = 6;

    public static String toString(int val){
        switch (val) {
        case kRecordEventActionStart: return "kRecordEventActionStart";
        case kRecordEventActionStop: return "kRecordEventActionStop";
        case kRecordEventActionPause: return "kRecordEventActionPause";
        case kRecordEventActionRsume: return "kRecordEventActionRsume";
        case kRecordEventActionUploading: return "kRecordEventActionUploading";
        case kRecordEventActionUploaded: return "kRecordEventActionUploaded";
        case kRecordEventActionError: return "kRecordEventActionError";
        default: return "unknown";
        }
    }
}
