//
// ****************************************************************
// Copyright(c) 2008-2013 uvisual,inc. All rights reserved.
// ****************************************************************
//
// Auto generated from: xx.def
// Warning: do not edit this file.
//
package com.juphoon.rtc.datacenter.cube.model;


import lombok.Data;

import java.util.List;
import java.util.Map;

@Data
public class EventMapPO {
    public long timestamp;
    public int type;
    public int eventNumber;
    public String uuid;
    public List<String> tags;
    public Map<String,Object> params;
    public long domainId;
    public long appId;
}
