//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\datac.c
// Warning: do not edit this file.
//
package DataCollection;

@SuppressWarnings("PMD")
public final class EventType{
    public static final int kEventTypeRecord = 0;

    public static String toString(int val){
        switch (val) {
        case kEventTypeRecord: return "kEventTypeRecord";
        default: return "unknown";
        }
    }
}
