//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\datac.c
// Warning: do not edit this file.
//
package DataCollection;

@SuppressWarnings("PMD")
public final class FlowStatus {
    public String uniqueId;
    public int type;
    public int status;
    public java.util.Map<String,String > params;
    public long domainId;
    public long appId;

    public FlowStatus() {
        this.uniqueId = "";
        this.type = (int)0;
        this.status = (int)0;
        this.params = null;
        this.domainId = (long)0;
        this.appId = (long)0;
    }

    public FlowStatus(String uniqueId,int type,int status,java.util.Map<String,String > params,long domainId,long appId) {
        this.uniqueId = uniqueId;
        this.type = type;
        this.status = status;
        this.params = params;
        this.domainId = domainId;
        this.appId = appId;
    }

    public static final class Holder {
        public Holder() {
        }
        public Holder(DataCollection.FlowStatus value) {
            this.value = value;
        }
        public DataCollection.FlowStatus value;
    }

    public static void __write(Common.OputStream __oput,DataCollection.FlowStatus __obj) {
        if (__obj == null) __obj = new DataCollection.FlowStatus();
        __oput.write(__obj.uniqueId);
        __oput.write(__obj.type);
        __oput.write(__obj.status);
        Common.StrStrMap.__write(__oput,__obj.params);
        __oput.write(__obj.domainId);
        __oput.write(__obj.appId);
    }

    public static DataCollection.FlowStatus __read(Common.IputStream __iput) throws Common.Exception {
        DataCollection.FlowStatus __obj = new DataCollection.FlowStatus();
        __obj.uniqueId = __iput.readString();
        __obj.type = __iput.readInt();
        __obj.status = __iput.readInt();
        __obj.params = Common.StrStrMap.__read(__iput);
        __obj.domainId = __iput.readLong();
        __obj.appId = __iput.readLong();
        return __obj;
    }

    public static void __textWrite(Common.OputStream __oput,String __name,DataCollection.FlowStatus __obj) {
        if (__obj == null) return;
        __oput.textStart(__name);
        __oput.textWrite("uniqueId",__obj.uniqueId);
        __oput.textWrite("type",__obj.type);
        __oput.textWrite("status",__obj.status);
        Common.StrStrMap.__textWrite(__oput,"params",__obj.params);
        __oput.textWrite("domainId",__obj.domainId);
        __oput.textWrite("appId",__obj.appId);
        __oput.textEnd();
    }

    public static DataCollection.FlowStatus __textRead(Common.IputStream __iput,String __name,int __idx) {
        if (!__iput.textStart(__name,__idx)) return null;
        DataCollection.FlowStatus __obj = new DataCollection.FlowStatus();
        __obj.uniqueId = __iput.textReadString("uniqueId",0,"");
        __obj.type = __iput.textReadInt("type",0,(int)0);
        __obj.status = __iput.textReadInt("status",0,(int)0);
        __obj.params = Common.StrStrMap.__textRead(__iput,"params",0);
        __obj.domainId = __iput.textReadLong("domainId",0,(long)0);
        __obj.appId = __iput.textReadLong("appId",0,(long)0);
        __iput.textEnd();
        return __obj;
    }
}
