//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\datac.c
// Warning: do not edit this file.
//
package DataCollection;

@SuppressWarnings("PMD")
public final class Metric {
    public long timestamp;
    public String serviceType;
    public String oid;
    public String version;
    public java.util.Map<String,String > params;
    public long domainId;
    public long appId;

    public Metric() {
        this.timestamp = (long)0;
        this.serviceType = "";
        this.oid = "";
        this.version = "";
        this.params = null;
        this.domainId = (long)0;
        this.appId = (long)0;
    }

    public Metric(long timestamp,String serviceType,String oid,String version,java.util.Map<String,String > params,long domainId,long appId) {
        this.timestamp = timestamp;
        this.serviceType = serviceType;
        this.oid = oid;
        this.version = version;
        this.params = params;
        this.domainId = domainId;
        this.appId = appId;
    }

    public static final class Holder {
        public Holder() {
        }
        public Holder(DataCollection.Metric value) {
            this.value = value;
        }
        public DataCollection.Metric value;
    }

    public static void __write(Common.OputStream __oput,DataCollection.Metric __obj) {
        if (__obj == null) __obj = new DataCollection.Metric();
        __oput.write(__obj.timestamp);
        __oput.write(__obj.serviceType);
        __oput.write(__obj.oid);
        __oput.write(__obj.version);
        Common.StrStrMap.__write(__oput,__obj.params);
        __oput.write(__obj.domainId);
        __oput.write(__obj.appId);
    }

    public static DataCollection.Metric __read(Common.IputStream __iput) throws Common.Exception {
        DataCollection.Metric __obj = new DataCollection.Metric();
        __obj.timestamp = __iput.readLong();
        __obj.serviceType = __iput.readString();
        __obj.oid = __iput.readString();
        __obj.version = __iput.readString();
        __obj.params = Common.StrStrMap.__read(__iput);
        __obj.domainId = __iput.readLong();
        __obj.appId = __iput.readLong();
        return __obj;
    }

    public static void __textWrite(Common.OputStream __oput,String __name,DataCollection.Metric __obj) {
        if (__obj == null) return;
        __oput.textStart(__name);
        __oput.textWrite("timestamp",__obj.timestamp);
        __oput.textWrite("serviceType",__obj.serviceType);
        __oput.textWrite("oid",__obj.oid);
        __oput.textWrite("version",__obj.version);
        Common.StrStrMap.__textWrite(__oput,"params",__obj.params);
        __oput.textWrite("domainId",__obj.domainId);
        __oput.textWrite("appId",__obj.appId);
        __oput.textEnd();
    }

    public static DataCollection.Metric __textRead(Common.IputStream __iput,String __name,int __idx) {
        if (!__iput.textStart(__name,__idx)) return null;
        DataCollection.Metric __obj = new DataCollection.Metric();
        __obj.timestamp = __iput.textReadLong("timestamp",0,(long)0);
        __obj.serviceType = __iput.textReadString("serviceType",0,"");
        __obj.oid = __iput.textReadString("oid",0,"");
        __obj.version = __iput.textReadString("version",0,"");
        __obj.params = Common.StrStrMap.__textRead(__iput,"params",0);
        __obj.domainId = __iput.textReadLong("domainId",0,(long)0);
        __obj.appId = __iput.textReadLong("appId",0,(long)0);
        __iput.textEnd();
        return __obj;
    }
}
