//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\datac.c
// Warning: do not edit this file.
//
package DataCollection;

@SuppressWarnings("PMD")
public final class MetricList {
    public static final class Holder {
        public Holder() {
        }
        public Holder(java.util.List<DataCollection.Metric > value) {
            this.value = value;
        }
        public java.util.List<DataCollection.Metric > value;
    }

    public static void __write(Common.OputStream __oput,java.util.List<DataCollection.Metric > __obj) {
        if (__obj == null)
            __oput.write((int)0);
        else {
            __oput.write((int)__obj.size());
            for(DataCollection.Metric m:__obj)
                DataCollection.Metric.__write(__oput,m);
        }
    }

    public static java.util.List<DataCollection.Metric > __read(Common.IputStream __iput) throws Common.Exception {
        java.util.List<DataCollection.Metric > __obj = new java.util.ArrayList<DataCollection.Metric >();
        int size = __iput.readInt();
        for (int i=0;i<size;i++) {
            DataCollection.Metric m = DataCollection.Metric.__read(__iput);
            __obj.add(m);
        }
        return __obj;
    }

    public static void __textWrite(Common.OputStream __oput,String __name,java.util.List<DataCollection.Metric > __obj) {
        if (__obj == null) return;
        __oput.textArray(__name);
        for(DataCollection.Metric m:__obj) {
            DataCollection.Metric.__textWrite(__oput,__name,m);
        }
    }

    public static java.util.List<DataCollection.Metric > __textRead(Common.IputStream __iput,String __name,int __idx) {
        java.util.List<DataCollection.Metric > __obj = new java.util.ArrayList<DataCollection.Metric >();
        int size = __iput.textCount(__name);
        for (int i=0;i<size;i++) {
            DataCollection.Metric m;
            if ((m = DataCollection.Metric.__textRead(__iput,__name,i)) != null)
                __obj.add(m);
        }
        return __obj;
    }
}

