//
// *****************************************************************************
// Copyright(c) 2017-2019 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: .\datac.c
// Warning: do not edit this file.
//
package DataCollection;

@SuppressWarnings("PMD")
public abstract class MetricCollectionServiceServer extends Common.ObjectServer {
    public abstract void metric_begin(Common.ServerCall __call,DataCollection.Metric metricInfo) throws Common.Exception;

    public final boolean __ex(Common.ServerCall __call,String __cmd,Common.IputStream __iput) throws Common.Exception {
        if (__cmd.compareTo("metric.MetricCollectionService.DataCollection") == 0) { __cmd_metric(__call,__iput);return true;} 
        return false;
    }

    public static void metric_end(Common.ServerCall __call,boolean __ret) {
        Common.VerList __vers = __call.verList();
        Common.OputStream __oput = new Common.OputStream();
        short __ver = (__vers != null)?__vers.ver(true):0;
        switch (__ver) {
        case 0:
            __oput.write(__ret);
            break;
        }
        __call.cmdResult(__ver,__oput);
    }

    private void __cmd_metric(Common.ServerCall __call,Common.IputStream __iput) throws Common.Exception {
        __outer: {
            Common.VerList __vers = __call.verList();
            DataCollection.Metric metricInfo;
            switch (__vers.ver(false)) {
            case 0:
                metricInfo = DataCollection.Metric.__read(__iput);
                break;
            default: break __outer;
            }
            __start(false);
            metric_begin(__call,metricInfo);
            return;
        }
        Common.OputStream __oput = new Common.OputStream();
        __oput.write((short)1);
        __oput.write((short)0);
        __call.cmdResult(1<<16,__oput);
    }
}
